name: Publish docker
on:
  push:
    tags:
      - 'docker/v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Set env
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:18})
    - uses: actions/checkout@master
    - name: Publish to GitHub Packages
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: totopolis/monik/service:${{ env.RELEASE_VERSION }}
        username: Totopolis
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        buildargs: VERSION=${{ env.RELEASE_VERSION }}
    - name: Publish to DockerHub
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: totopolis/monik/service:${{ env.RELEASE_VERSION }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildargs: VERSION=${{ env.RELEASE_VERSION }}